global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'auth'
    static_configs:
      - targets: ['auth:4000']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'chat'
    static_configs:
      - targets: ['chat:4001']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'game'
    static_configs:
      - targets: ['game:4002']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'user'
    static_configs:
      - targets: ['user:4006']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'databases'
    static_configs:
      - targets: ['databases:4007']
    metrics_path: /metrics
    scrape_interval: 15s

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: /_prometheus/metrics
    scrape_interval: 30s