services:
  sqlite:
    build: ./Sqlite
    container_name: sqlite
    env_file:
      - ../../.env
    volumes:
      - sqlite_data:/app/data
    networks:
      - app-net

volumes:
  sqlite_data:


networks:
  app-net:

