services:
  frontend:
    build: ./
    container_name: frontend
    env_file:
      - ../.env
    ports:

      - "4443:443"
    volumes:

      - ../ssl/certs:/etc/nginx/ssl:ro
      - frontend_node_modules:/app/node_modules
    networks:
      - app-net
    restart: unless-stopped

volumes:
  frontend_node_modules: {}

networks:
  app-net:


